sudo: required
services:
    - docker
before_install:
    - docker build -t ddinesherode/multicontainer -f ./client/Dockerfile.dev	
script:
    - docker run ddinesherode/multicontainer npm test -- --coverage
after_success:
    - docker build -t ddinesherode/multi-client ./client
    - docker build -t ddinesherode/multi-nginx ./nginx
    - docker build -t ddinesherode/multi-server ./server
    - docker build -t ddinesherode/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ddinesherode/multi-client
    - docker push ddinesherode/multi-nginx
    - docker push ddinesherode/multi-server
    - docker push ddinesherode/multi-worker